# Generated by Django 5.1.4 on 2025-02-22 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaverequest',
            name='applied_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
