# Generated by Django 5.1.4 on 2025-03-20 19:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0004_leaverequest_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.PositiveBigIntegerField(default=20)),
                ('leave_type', models.CharField(choices=[('sick', 'Sick'), ('emergency', 'Emergency'), ('vacation', 'Vacation'), ('unpaid', 'Unpaid'), ('other', 'Other')], default='unpaid', max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='leave_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_types', to='leave.leavetype'),
        ),
        migrations.DeleteModel(
            name='leave',
        ),
    ]
