# Generated by Django 5.1.4 on 2025-01-10 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='first_time',
            field=models.BooleanField(default=True),
        ),
    ]
