# Generated by Django 5.1.4 on 2025-01-25 15:56

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_user_first_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='user/ranks/%Y/%m/%d/', validators=[account.models.validate_five_mb_image_size]),
        ),
    ]
