# Generated by Django 5.1.4 on 2025-04-24 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_user_report_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_otp',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
