# Generated by Django 5.1.4 on 2025-02-27 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0005_alter_task_due_date_timelog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('HIGH', 'High'), ('LOW', 'Low'), ('MEDIUM', 'medium')], default='LOW', max_length=20),
        ),
    ]
