# Generated by Django 5.1.4 on 2025-02-28 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0007_alter_task_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtask',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='sub_task/'),
        ),
        migrations.AddField(
            model_name='subtask',
            name='task_upload_file',
            field=models.FileField(blank=True, null=True, upload_to='sub_task/'),
        ),
        migrations.AddField(
            model_name='task',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='task/'),
        ),
        migrations.AddField(
            model_name='task',
            name='task_upload_file',
            field=models.FileField(blank=True, null=True, upload_to='task/'),
        ),
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
