# Generated by Django 5.1.4 on 2025-04-08 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0010_category_task_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='timelog',
            name='is_holiday',
            field=models.BooleanField(default=False),
        ),
    ]
