# Generated by Django 5.1.4 on 2025-04-09 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0011_timelog_is_holiday'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtask',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
